development:
  adapter: postgresql
  host: localhost
  port: 5432
  username: olancheg
  password: 
  database: rytp_development
  encoding: utf8

test:
  adapter: sqlite3
  database: db/test.sqlite3
  pool: 5
  timeout: 5000

production:
  adapter: postgresql
  host: localhost
  port: 5432
  username: postgres
  password: system
  database: rytp
  encoding: utf8

